In [135]:
import numpy as np

In [136]:
import pandas as pd
import os
import joblib

import warnings
 
# 屏蔽某个特定警告类型
warnings.filterwarnings('ignore', category=UserWarning)
 
# 屏蔽所有警告
warnings.filterwarnings('ignore')

In [137]:
stock_pool=pd.read_csv("all_stock_pool.csv")
stock_pool.index = index
stock_pool

,000001.SZ,000002.SZ,000004.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,000012.SZ,...,605507.SH,605555.SH,605566.SH,605567.SH,605577.SH,605580.SH,605588.SH,605589.SH,605598.SH,605599.SH
20141027,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20141028,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20141029,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20141030,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20141031,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20241021,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20241022,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20241023,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20241024,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20241025,False,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [138]:
stock_basic = pd.read_csv("stock_basic.csv")
stock_basic

        ts_code  symbol  name area industry  list_date
0     000001.SZ       1  平安银行   深圳       银行   19910403
1     000002.SZ       2   万科A   深圳     全国地产   19910129
2     000004.SZ       4  国华网安   深圳     软件服务   19910114
3     000006.SZ       6  深振业A   深圳     区域地产   19920427
4     000007.SZ       7   全新好   深圳     其他商业   19920413
...         ...     ...   ...  ...      ...        ...
4530  605580.SH  605580  恒盛能源   浙江     供气供热   20210819
4531  605588.SH  605588  冠石科技   江苏      元器件   20210812
4532  605589.SH  605589  圣泉集团   山东     化工原料   20210810
4533  605598.SH  605598  上海港湾   上海     建筑工程   20210917
4534  605599.SH  605599  菜百股份   北京       服饰   20210909

[4535 rows x 6 columns]

In [139]:
trade_cal = pd.read_csv("trade_cal.csv")
trade_cal

     exchange  cal_date  is_open  pretrade_date
0         SSE  20141027        1       20141024
1         SSE  20141028        1       20141027
2         SSE  20141029        1       20141028
3         SSE  20141030        1       20141029
4         SSE  20141031        1       20141030
...       ...       ...      ...            ...
2427      SSE  20241021        1       20241018
2428      SSE  20241022        1       20241021
2429      SSE  20241023        1       20241022
2430      SSE  20241024        1       20241023
2431      SSE  20241025        1       20241024

[2432 rows x 4 columns]

In [140]:
custom_date = pd.read_csv("custom_date.csv")
start_date=str(custom_date.start_date[0])
end_date=str(custom_date.end_date[0])
print(start_date)
print(end_date)

20141027
20241027

In [141]:
index = trade_cal.cal_date.tolist()
index

[20141027,
 20141028,
 20141029,
 20141030,
 20141031,
 20141103,
 20141104,
 20141105,
 20141106,
 20141107,
 20141110,
 20141111,
 20141112,
 20141113,
 20141114,
 20141117,
 20141118,
 20141119,
 20141120,
 20141121,
 20141124,
 20141125,
 20141126,
 20141127,
 20141128,
 20141201,
 20141202,
 20141203,
 20141204,
 20141205,
 20141208,
 20141209,
 20141210,
 20141211,
 20141212,
 20141215,
 20141216,
 20141217,
 20141218,
 20141219,
 20141222,
 20141223,
 20141224,
 20141225,
 20141226,
 20141229,
 20141230,
 20141231,
 20150105,
 20150106,
 20150107,
 20150108,
 20150109,
 20150112,
 20150113,
 20150114,
 20150115,
 20150116,
 20150119,
 20150120,
 20150121,
 20150122,
 20150123,
 20150126,
 20150127,
 20150128,
 20150129,
 20150130,
 20150202,
 20150203,
 20150204,
 20150205,
 20150206,
 20150209,
 20150210,
 20150211,
 20150212,
 20150213,
 20150216,
 20150217,
 20150225,
 20150226,
 20150227,
 20150302,
 20150303,
 20150304,
 20150305,
 20150306,
 20150309,
 20150310,
 20150311,
 20150312,
 20150313,
 20150316,
 20150317,
 20150318,
 20150319,
 20150320,
 20150323,
 20150324,
 20150325,
 20150326,
 20150327,
 20150330,
 20150331,
 20150401,
 20150402,
 20150403,
 20150407,
 20150408,
 20150409,
 20150410,
 20150413,
 20150414,
 20150415,
 20150416,
 20150417,
 20150420,
 20150421,
 20150422,
 20150423,
 20150424,
 20150427,
 20150428,
 20150429,
 20150430,
 20150504,
 20150505,
 20150506,
 20150507,
 20150508,
 20150511,
 20150512,
 20150513,
 20150514,
 20150515,
 20150518,
 20150519,
 20150520,
 20150521,
 20150522,
 20150525,
 20150526,
 20150527,
 20150528,
 20150529,
 20150601,
 20150602,
 20150603,
 20150604,
 20150605,
 20150608,
 20150609,
 20150610,
 20150611,
 20150612,
 20150615,
 20150616,
 20150617,
 20150618,
 20150619,
 20150623,
 20150624,
 20150625,
 20150626,
 20150629,
 20150630,
 20150701,
 20150702,
 20150703,
 20150706,
 20150707,
 20150708,
 20150709,
 20150710,
 20150713,
 20150714,
 20150715,
 20150716,
 20150717,
 20150720,
 20150721,
 20150722,
 20150723,
 20150724,
 20150727,
 20150728,
 20150729,
 20150730,
 20150731,
 20150803,
 20150804,
 20150805,
 20150806,
 20150807,
 20150810,
 20150811,
 20150812,
 20150813,
 20150814,
 20150817,
 20150818,
 20150819,
 20150820,
 20150821,
 20150824,
 20150825,
 20150826,
 20150827,
 20150828,
 20150831,
 20150901,
 20150902,
 20150907,
 20150908,
 20150909,
 20150910,
 20150911,
 20150914,
 20150915,
 20150916,
 20150917,
 20150918,
 20150921,
 20150922,
 20150923,
 20150924,
 20150925,
 20150928,
 20150929,
 20150930,
 20151008,
 20151009,
 20151012,
 20151013,
 20151014,
 20151015,
 20151016,
 20151019,
 20151020,
 20151021,
 20151022,
 20151023,
 20151026,
 20151027,
 20151028,
 20151029,
 20151030,
 20151102,
 20151103,
 20151104,
 20151105,
 20151106,
 20151109,
 20151110,
 20151111,
 20151112,
 20151113,
 20151116,
 20151117,
 20151118,
 20151119,
 20151120,
 20151123,
 20151124,
 20151125,
 20151126,
 20151127,
 20151130,
 20151201,
 20151202,
 20151203,
 20151204,
 20151207,
 20151208,
 20151209,
 20151210,
 20151211,
 20151214,
 20151215,
 20151216,
 20151217,
 20151218,
 20151221,
 20151222,
 20151223,
 20151224,
 20151225,
 20151228,
 20151229,
 20151230,
 20151231,
 20160104,
 20160105,
 20160106,
 20160107,
 20160108,
 20160111,
 20160112,
 20160113,
 20160114,
 20160115,
 20160118,
 20160119,
 20160120,
 20160121,
 20160122,
 20160125,
 20160126,
 20160127,
 20160128,
 20160129,
 20160201,
 20160202,
 20160203,
 20160204,
 20160205,
 20160215,
 20160216,
 20160217,
 20160218,
 20160219,
 20160222,
 20160223,
 20160224,
 20160225,
 20160226,
 20160229,
 20160301,
 20160302,
 20160303,
 20160304,
 20160307,
 20160308,
 20160309,
 20160310,
 20160311,
 20160314,
 20160315,
 20160316,
 20160317,
 20160318,
 20160321,
 20160322,
 20160323,
 20160324,
 20160325,
 20160328,
 20160329,
 20160330,
 20160331,
 20160401,
 20160405,
 20160406,
 20160407,
 20160408,
 20160411,
 20160412,
 20160413,
 20160414,
 20160415,
 20160418,
 20160419,
 20160420,
 20160421,
 20160422,
 20160425,
 20160426,
 20160427,
 20160428,
 20160429,
 20160503,
 20160504,
 20160505,
 20160506,
 20160509,
 20160510,
 20160511,
 20160512,
 20160513,
 20160516,
 20160517,
 20160518,
 20160519,
 20160520,
 20160523,
 20160524,
 20160525,
 20160526,
 20160527,
 20160530,
 20160531,
 20160601,
 20160602,
 20160603,
 20160606,
 20160607,
 20160608,
 20160613,
 20160614,
 20160615,
 20160616,
 20160617,
 20160620,
 20160621,
 20160622,
 20160623,
 20160624,
 20160627,
 20160628,
 20160629,
 20160630,
 20160701,
 20160704,
 20160705,
 20160706,
 20160707,
 20160708,
 20160711,
 20160712,
 20160713,
 20160714,
 20160715,
 20160718,
 20160719,
 20160720,
 20160721,
 20160722,
 20160725,
 20160726,
 20160727,
 20160728,
 20160729,
 20160801,
 20160802,
 20160803,
 20160804,
 20160805,
 20160808,
 20160809,
 20160810,
 20160811,
 20160812,
 20160815,
 20160816,
 20160817,
 20160818,
 20160819,
 20160822,
 20160823,
 20160824,
 20160825,
 20160826,
 20160829,
 20160830,
 20160831,
 20160901,
 20160902,
 20160905,
 20160906,
 20160907,
 20160908,
 20160909,
 20160912,
 20160913,
 20160914,
 20160919,
 20160920,
 20160921,
 20160922,
 20160923,
 20160926,
 20160927,
 20160928,
 20160929,
 20160930,
 20161010,
 20161011,
 20161012,
 20161013,
 20161014,
 20161017,
 20161018,
 20161019,
 20161020,
 20161021,
 20161024,
 20161025,
 20161026,
 20161027,
 20161028,
 20161031,
 20161101,
 20161102,
 20161103,
 20161104,
 20161107,
 20161108,
 20161109,
 20161110,
 20161111,
 20161114,
 20161115,
 20161116,
 20161117,
 20161118,
 20161121,
 20161122,
 20161123,
 20161124,
 20161125,
 20161128,
 20161129,
 20161130,
 20161201,
 20161202,
 20161205,
 20161206,
 20161207,
 20161208,
 20161209,
 20161212,
 20161213,
 20161214,
 20161215,
 20161216,
 20161219,
 20161220,
 20161221,
 20161222,
 20161223,
 20161226,
 20161227,
 20161228,
 20161229,
 20161230,
 20170103,
 20170104,
 20170105,
 20170106,
 20170109,
 20170110,
 20170111,
 20170112,
 20170113,
 20170116,
 20170117,
 20170118,
 20170119,
 20170120,
 20170123,
 20170124,
 20170125,
 20170126,
 20170203,
 20170206,
 20170207,
 20170208,
 20170209,
 20170210,
 20170213,
 20170214,
 20170215,
 20170216,
 20170217,
 20170220,
 20170221,
 20170222,
 20170223,
 20170224,
 20170227,
 20170228,
 20170301,
 20170302,
 20170303,
 20170306,
 20170307,
 20170308,
 20170309,
 20170310,
 20170313,
 20170314,
 20170315,
 20170316,
 20170317,
 20170320,
 20170321,
 20170322,
 20170323,
 20170324,
 20170327,
 20170328,
 20170329,
 20170330,
 20170331,
 20170405,
 20170406,
 20170407,
 20170410,
 20170411,
 20170412,
 20170413,
 20170414,
 20170417,
 20170418,
 20170419,
 20170420,
 20170421,
 20170424,
 20170425,
 20170426,
 20170427,
 20170428,
 20170502,
 20170503,
 20170504,
 20170505,
 20170508,
 20170509,
 20170510,
 20170511,
 20170512,
 20170515,
 20170516,
 20170517,
 20170518,
 20170519,
 20170522,
 20170523,
 20170524,
 20170525,
 20170526,
 20170531,
 20170601,
 20170602,
 20170605,
 20170606,
 20170607,
 20170608,
 20170609,
 20170612,
 20170613,
 20170614,
 20170615,
 20170616,
 20170619,
 20170620,
 20170621,
 20170622,
 20170623,
 20170626,
 20170627,
 20170628,
 20170629,
 20170630,
 20170703,
 20170704,
 20170705,
 20170706,
 20170707,
 20170710,
 20170711,
 20170712,
 20170713,
 20170714,
 20170717,
 20170718,
 20170719,
 20170720,
 20170721,
 20170724,
 20170725,
 20170726,
 20170727,
 20170728,
 20170731,
 20170801,
 20170802,
 20170803,
 20170804,
 20170807,
 20170808,
 20170809,
 20170810,
 20170811,
 20170814,
 20170815,
 20170816,
 20170817,
 20170818,
 20170821,
 20170822,
 20170823,
 20170824,
 20170825,
 20170828,
 20170829,
 20170830,
 20170831,
 20170901,
 20170904,
 20170905,
 20170906,
 20170907,
 20170908,
 20170911,
 20170912,
 20170913,
 20170914,
 20170915,
 20170918,
 20170919,
 20170920,
 20170921,
 20170922,
 20170925,
 20170926,
 20170927,
 20170928,
 20170929,
 20171009,
 20171010,
 20171011,
 20171012,
 20171013,
 20171016,
 20171017,
 20171018,
 20171019,
 20171020,
 20171023,
 20171024,
 20171025,
 20171026,
 20171027,
 20171030,
 20171031,
 20171101,
 20171102,
 20171103,
 20171106,
 20171107,
 20171108,
 20171109,
 20171110,
 20171113,
 20171114,
 20171115,
 20171116,
 20171117,
 20171120,
 20171121,
 20171122,
 20171123,
 20171124,
 20171127,
 20171128,
 20171129,
 20171130,
 20171201,
 20171204,
 20171205,
 20171206,
 20171207,
 20171208,
 20171211,
 20171212,
 20171213,
 20171214,
 20171215,
 20171218,
 20171219,
 20171220,
 20171221,
 20171222,
 20171225,
 20171226,
 20171227,
 20171228,
 20171229,
 20180102,
 20180103,
 20180104,
 20180105,
 20180108,
 20180109,
 20180110,
 20180111,
 20180112,
 20180115,
 20180116,
 20180117,
 20180118,
 20180119,
 20180122,
 20180123,
 20180124,
 20180125,
 20180126,
 20180129,
 20180130,
 20180131,
 20180201,
 20180202,
 20180205,
 20180206,
 20180207,
 20180208,
 20180209,
 20180212,
 20180213,
 20180214,
 20180222,
 20180223,
 20180226,
 20180227,
 20180228,
 20180301,
 20180302,
 20180305,
 20180306,
 20180307,
 20180308,
 20180309,
 20180312,
 20180313,
 20180314,
 20180315,
 20180316,
 20180319,
 20180320,
 20180321,
 20180322,
 20180323,
 20180326,
 20180327,
 20180328,
 20180329,
 20180330,
 20180402,
 20180403,
 20180404,
 20180409,
 20180410,
 20180411,
 20180412,
 20180413,
 20180416,
 20180417,
 20180418,
 20180419,
 20180420,
 20180423,
 20180424,
 20180425,
 20180426,
 20180427,
 20180502,
 20180503,
 20180504,
 20180507,
 20180508,
 20180509,
 20180510,
 20180511,
 20180514,
 20180515,
 20180516,
 20180517,
 20180518,
 20180521,
 20180522,
 20180523,
 20180524,
 20180525,
 20180528,
 20180529,
 20180530,
 20180531,
 20180601,
 20180604,
 20180605,
 20180606,
 20180607,
 20180608,
 20180611,
 20180612,
 20180613,
 20180614,
 20180615,
 20180619,
 20180620,
 20180621,
 20180622,
 20180625,
 20180626,
 20180627,
 20180628,
 20180629,
 20180702,
 20180703,
 20180704,
 20180705,
 20180706,
 20180709,
 20180710,
 20180711,
 20180712,
 20180713,
 20180716,
 20180717,
 20180718,
 20180719,
 20180720,
 20180723,
 20180724,
 20180725,
 20180726,
 20180727,
 20180730,
 20180731,
 20180801,
 20180802,
 20180803,
 20180806,
 20180807,
 20180808,
 20180809,
 20180810,
 20180813,
 20180814,
 20180815,
 20180816,
 20180817,
 20180820,
 20180821,
 20180822,
 20180823,
 20180824,
 20180827,
 20180828,
 20180829,
 20180830,
 20180831,
 20180903,
 20180904,
 20180905,
 20180906,
 20180907,
 20180910,
 20180911,
 20180912,
 20180913,
 20180914,
 20180917,
 20180918,
 20180919,
 20180920,
 20180921,
 20180925,
 20180926,
 20180927,
 20180928,
 20181008,
 20181009,
 20181010,
 20181011,
 20181012,
 20181015,
 20181016,
 20181017,
 20181018,
 20181019,
 20181022,
 20181023,
 20181024,
 20181025,
 20181026,
 20181029,
 20181030,
 20181031,
 20181101,
 20181102,
 20181105,
 20181106,
 20181107,
 20181108,
 20181109,
 20181112,
 20181113,
 20181114,
 20181115,
 20181116,
 20181119,
 20181120,
 20181121,
 20181122,
 20181123,
 20181126,
 20181127,
 ...]

In [144]:
# factor_name = "vol_w_downshadow_std_1M"
# factor_name="total_mv"
# factor_name="mmt_intraday_M"
# factor_name="liq_amihud_avg_1M"
factor_name="corr_ret_turn_post_1M"
return_name="return_-5"

In [145]:
factor_df=pd.read_csv(factor_name+".csv")
factor_df.index=index
return_df=pd.read_csv(return_name+".csv")
return_df.index=index

In [146]:
factor_df

,000001.SZ,000002.SZ,000004.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,000012.SZ,...,605507.SH,605555.SH,605566.SH,605567.SH,605577.SH,605580.SH,605588.SH,605589.SH,605598.SH,605599.SH
20141027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20241021,-0.137279,-0.304265,-0.382172,-0.200997,-0.193830,-0.278557,-0.092848,-0.299255,-0.481106,-0.357920,...,-0.103879,-0.195927,-0.521619,-0.311668,-0.070275,-0.207829,-0.235359,-0.172123,-0.241750,-0.461936
20241022,-0.172534,-0.337806,-0.518933,-0.024982,-0.223560,-0.280649,-0.150645,-0.321221,-0.478697,-0.354163,...,-0.131788,-0.171002,-0.571214,-0.364836,-0.109548,-0.245341,-0.353266,-0.198603,-0.245130,-0.501620
20241023,-0.180507,-0.329120,-0.511873,-0.027868,-0.163955,-0.328085,-0.216676,-0.348038,-0.480933,-0.355703,...,-0.155087,-0.225817,-0.623520,-0.397577,-0.169385,-0.250965,-0.378813,-0.215634,-0.200907,-0.523211
20241024,-0.179137,-0.276930,-0.482577,0.112323,-0.044525,-0.313527,-0.202226,-0.352592,-0.485916,-0.378641,...,-0.167959,-0.203101,-0.606763,-0.371174,-0.160366,-0.236401,-0.384827,-0.263698,-0.191395,-0.526454
20241025,-0.158181,-0.254388,-0.415003,0.039503,-0.133862,-0.351233,-0.270953,-0.374955,-0.438536,-0.439414,...,-0.207155,-0.234418,-0.618670,-0.389179,-0.188023,-0.272307,-0.391630,-0.305764,-0.191850,-0.572304

In [147]:
return_df

,000001.SZ,000002.SZ,000004.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,000012.SZ,...,605507.SH,605555.SH,605566.SH,605567.SH,605577.SH,605580.SH,605588.SH,605589.SH,605598.SH,605599.SH
20141027,0.108782,0.059226,0.053950,0.116071,0.026731,0.078778,0.019577,0.024691,0.154746,0.049598,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141028,0.066863,0.041020,0.036476,0.069808,-0.001195,0.025758,0.018377,-0.026731,0.106195,0.040736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141029,0.050485,0.007592,-0.042876,0.062925,0.000579,0.008924,0.017652,-0.030340,0.089219,0.020860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141030,0.039310,0.016340,-0.052446,0.072041,0.035545,0.025415,0.024691,-0.009732,0.112360,0.020888,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20141031,-0.010879,0.000000,-0.038462,-0.023885,-0.007038,0.145409,0.002313,-0.029268,-0.007946,-0.014103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20241021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20241022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20241023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20241024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20241025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 股票池选取

In [148]:
factor_df.mask(stock_pool,np.nan,inplace = True)
return_df.mask(stock_pool,np.nan,inplace = True)

In [149]:
import statsmodels.api as sm

In [150]:
# 去极值
def winsorize(factor, std=3):
    r = factor.copy()
    r_mean = r.mean()
    r_std = r.std()
    edge_up = r_mean + std * r_std
    edge_low = r_mean - std * r_std
    r[r>edge_up]=edge_up
    r[r<edge_low]=edge_low
    return r

In [151]:
# 标准化
def standardize(factor, ty=2):
    r = factor.copy()
    if ty==1:
        r = (r-r.min())/(r.max()-r.min())
    elif ty==2:
        r = (r-r.mean())/r.std()
#     elif ty==3:
#         r= r/10**np.ceil(np.log10(r.abs().max()))
    return r

In [152]:
# 中性化
def neutral(x,y,industry = True,mkt_cap = False):
    result = sm.WLS(y.astype(float), x.astype(float)).fit()
#     print(y)
#     print(x)
    return result.resid

In [153]:
# x=new_industry_df
# y=current_df.factor
# result = sm.WLS(y.astype(float), x.astype(float)).fit()
# print(result.resid)

In [154]:
# current_df.factor

In [155]:
# new_industry_df.to_csv("test.csv")

In [156]:
# industry_df.iloc[10:20]

In [157]:
# current_df

In [158]:
# for index, row in trade_cal.iterrows():
for i in range(2420,trade_cal.shape[0]):
    row = trade_cal.iloc[i]
    current_date = row.cal_date
#     print(index, trade_cal.shape[0],current_date)
    print(i, trade_cal.shape[0],current_date)
    current_df =pd.DataFrame({"factor":factor_df.loc[current_date],"return":return_df.loc[current_date]})
    current_df.dropna(inplace=True)
    if current_df.shape[0]==0:
        continue
    current_df["factor"]=winsorize(current_df.factor)
    current_df["factor"]=standardize(current_df.factor)

    lnMarketCap_df=pd.read_csv("lnMarketCap/"+str(current_date)+".csv")
    lnMarketCap_df.set_index("ts_code",inplace=True)

    industry_df = pd.read_csv("industry/"+str(current_date)+".csv")
    industry_df.set_index("ts_code",inplace=True)
    new_industry_df = pd.DataFrame(index= current_df.index.tolist(),columns=industry_df.columns)
    for col in industry_df.columns:
        new_industry_df[col]=industry_df[col]
    new_industry_df["lnMarketCap"]=lnMarketCap_df["lnMarketCap"].copy()
    
    current_df["factor"]=neutral(new_industry_df,current_df.factor)
    
    current_df.sort_values(by="factor",inplace=True)#从小到大排序

    return_sum_10_stock = current_df["return"][0:10].sum()
    corr_spearman = current_df.corr(method='spearman').iloc[0][1]
    info_df=pd.DataFrame({"return_sum_10_stock":return_sum_10_stock,"corr_spearman":corr_spearman},index=[current_date])
    break
    
# current_df
# new_industry_df
# print(current_df["return"][0:10])
# print(return_sum)
# print(current_date)
# info_df

2420 2432 20241010

In [159]:
# first_num = 5 # 前几只股票 因子从小到大排序
step = 5 # 交易周期

In [160]:
industry_neutral = True
# industry_neutral = False
lnMarketCap_neutral = True
# lnMarketCap_neutral = False

In [161]:
zz500=pd.read_csv("zz500.csv")

@joblib.delayed
def task(current_date,i):
    
    current_df =pd.DataFrame({"factor":factor_df.loc[current_date],"return":return_df.loc[current_date]})
    current_df.dropna(inplace=True)
    if current_df.shape[0]==0:
        return pd.DataFrame()
    
    current_df["factor"]=winsorize(current_df.factor)
    current_df["factor"]=standardize(current_df.factor)

    if industry_neutral == True:
        industry_df = pd.read_csv("industry/"+str(current_date)+".csv")
        industry_df.set_index("ts_code",inplace=True)
        new_industry_df = pd.DataFrame(index= current_df.index.tolist(),columns=industry_df.columns)
        for col in industry_df.columns:
            new_industry_df[col]=industry_df[col]

    if lnMarketCap_neutral == True:
        lnMarketCap_df=pd.read_csv("lnMarketCap/"+str(current_date)+".csv")
        lnMarketCap_df.set_index("ts_code",inplace=True)
        new_industry_df["lnMarketCap"]=lnMarketCap_df["lnMarketCap"].copy()

    if industry_neutral == True:
        current_df["factor"]=neutral(new_industry_df,current_df.factor)
    
    current_df.sort_values(by="factor",inplace=True)#从小到大排序
    
    single_group_num = int(current_df.shape[0]/10)
    
    group01 = current_df["return"][0:single_group_num].mean()
    group02 = current_df["return"][single_group_num:2*single_group_num].mean()
    group03 = current_df["return"][2*single_group_num:3*single_group_num].mean()
    group04 = current_df["return"][3*single_group_num:4*single_group_num].mean()
    group05 = current_df["return"][4*single_group_num:5*single_group_num].mean()
    group06 = current_df["return"][5*single_group_num:6*single_group_num].mean()
    group07 = current_df["return"][6*single_group_num:7*single_group_num].mean()
    group08 = current_df["return"][7*single_group_num:8*single_group_num].mean()
    group09 = current_df["return"][8*single_group_num:9*single_group_num].mean()
    group10 = current_df["return"][9*single_group_num:].mean()
    
#     return_mean_stock = current_df["return"][0:first_num].mean()
    corr_spearman = current_df.corr(method='spearman').iloc[0][1]
    info_df=pd.DataFrame({"group01":group01,
                          "group02":group02,
                          "group03":group03,
                          "group04":group04,
                          "group05":group05,
                          "group06":group06,
                          "group07":group07,
                          "group08":group08,
                          "group09":group09,
                          "group10":group10,
                          "corr_spearman":corr_spearman,
                          "zz500_future_5":zz500.iloc[i].future_5,
                          "current_date":current_date},index=[current_date])
    return info_df

tasks=[]
i=0
while i<trade_cal.shape[0]:
#     print(i,trade_cal.shape[0])
#     if i<2400:
#         i=i+step
#         continue
    current_date = trade_cal.cal_date[i]
    tasks.append(task(current_date,i))
    i=i+step    
    
df = pd.concat(
    joblib.Parallel(n_jobs=5, verbose=10)(
        tasks
    ), axis=0)

[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   3 tasks      | elapsed:    2.2s
[Parallel(n_jobs=5)]: Done   8 tasks      | elapsed:    2.9s
[Parallel(n_jobs=5)]: Done  15 tasks      | elapsed:    3.6s
[Parallel(n_jobs=5)]: Done  22 tasks      | elapsed:    3.9s
[Parallel(n_jobs=5)]: Done  31 tasks      | elapsed:    4.6s
[Parallel(n_jobs=5)]: Done  40 tasks      | elapsed:    5.0s
[Parallel(n_jobs=5)]: Done  51 tasks      | elapsed:    5.7s
[Parallel(n_jobs=5)]: Done  62 tasks      | elapsed:    6.5s
[Parallel(n_jobs=5)]: Done  75 tasks      | elapsed:    7.4s
[Parallel(n_jobs=5)]: Done  88 tasks      | elapsed:    8.5s
[Parallel(n_jobs=5)]: Done 103 tasks      | elapsed:    9.6s
[Parallel(n_jobs=5)]: Done 118 tasks      | elapsed:   10.9s
[Parallel(n_jobs=5)]: Done 135 tasks      | elapsed:   12.3s
[Parallel(n_jobs=5)]: Done 152 tasks      | elapsed:   13.9s
[Parallel(n_jobs=5)]: Done 171 tasks      | elapsed:   15.7s
[Parallel(n_jobs=5)]: Done 190 tasks      | elapsed:   17.4s
[Parallel(n_jobs=5)]: Done 211 tasks      | elapsed:   19.5s
[Parallel(n_jobs=5)]: Done 232 tasks      | elapsed:   21.7s
[Parallel(n_jobs=5)]: Done 255 tasks      | elapsed:   24.1s
[Parallel(n_jobs=5)]: Done 278 tasks      | elapsed:   26.5s
[Parallel(n_jobs=5)]: Done 303 tasks      | elapsed:   29.1s
[Parallel(n_jobs=5)]: Done 328 tasks      | elapsed:   31.9s
[Parallel(n_jobs=5)]: Done 355 tasks      | elapsed:   35.2s
[Parallel(n_jobs=5)]: Done 382 tasks      | elapsed:   38.5s
[Parallel(n_jobs=5)]: Done 411 tasks      | elapsed:   42.1s
[Parallel(n_jobs=5)]: Done 440 tasks      | elapsed:   45.7s
[Parallel(n_jobs=5)]: Done 471 tasks      | elapsed:   49.4s
[Parallel(n_jobs=5)]: Done 487 out of 487 | elapsed:   51.1s finished

In [162]:
# df

In [163]:
df.dropna(inplace=True)
df.index= pd.to_datetime(df.index.tolist(),format="%Y%m%d")
df.to_csv("backtest_"+factor_name+".csv",index=0)

In [85]:
# df.return_mean_stock.cumsum().plot()

In [52]:
# df.corr_spearman.cumsum().plot()

In [30]:
# df

In [31]:
# current_date=20240912
# current_df =pd.DataFrame({"factor":factor_df.loc[current_date],"return":return_df.loc[current_date]})
# current_df.dropna(inplace=True)
# current_df.sort_values(by="factor",inplace=True)#从小到大排序
# return_sum_10_stock = current_df["return"][0:10].mean()
# corr_spearman = current_df.corr(method='spearman').iloc[0][1]
# info_df=pd.DataFrame({"return_sum_10_stock":return_sum_10_stock,"corr_spearman":corr_spearman},index=[current_date])

In [32]:
# current_df

In [33]:
# df.tail(30)